// COMMENTS ACTIONS
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_CURRENTUSER = "SET_CURRENTUSER";
export const UPVOTE_COMMENT = "UPVOTE_COMMENT";
export const DOWNVOTE_COMMENT = "DOWNVOTE_COMMENT";
export const RESET_SCORE = "RESET_SCORE";
export const ADD_REPLY = "ADD_REPLY";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

// REPLIES ACTIONS
export const UPVOTE_REPLY = "UPVOTE_REPLY";
export const DOWNVOTE_REPLY = "DOWNVOTE_REPLY";
export const RESET_REPLY_SCORE = "RESET_REPLY_SCORE";
export const ADD_NESTED_REPLY = "ADD_NESTED_REPLY";
export const UPDATE_REPLY = "UPDATE_REPLY";
export const DELETE_REPLY = "DELETE_REPLY";
