export const SET_COMMENTS = "SET_COMMENTS";
export const SET_CURRENTUSER = "SET_CURRENTUSER";
export const UPVOTE_COMMENT = "UPVOTE_COMMENT";
export const DOWNVOTE_COMMENT = "DOWNVOTE_COMMENT";
export const ADD_REPLY = "ADD_REPLY";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
